import { createStore } from './createStore.js';

/** دامنه adminUi — state موقت فرم/مودال/پنل */
export const adminUiStore = createStore({
  adminSeoHubKey: null,
  adminGscRange: '28d',
  adminGscInspectUrl: '',
  adminGscInspectResult: null,
  adminFrontEditOpen: false,
  adminFrontEditForm: { title: '', description: '', slug: '', indexable: true, focusKeywords: '', canonical: '', ogImage: '', faq: [] },
  adminAuthOpen: false,
  adminAuthPhone: '',
  adminAuthOtp: '',
  adminAuthPassword: '',
  adminAuthMethod: 'otp',
  adminAuthError: '',
  adminAuthLoading: false,
  adminAuthOtpTimer: 0,
  adminSellerFilter: 'all',
  adminSellerSearch: '',
  adminSellerDetailId: null,
  adminProductFilter: 'all',
  adminProductSearch: '',
  adminProductDetailId: null,
  adminOrderFilter: 'all',
  adminOrderSearch: '',
  adminOrderDetailId: null,
  adminOrderNote: '',
  adminCouponFormOpen: false,
  adminCouponForm: { code: '', type: 'percent', value: '', minCart: '', maxUses: '', maxPerUser: '', startDate: '', endDate: '', status: 'active' },
  adminTicketFilter: 'all',
  adminTicketDetailId: null,
  adminTicketReply: '',
  adminBuyerSearch: '',
  adminBuyerDetailId: null,
  adminRejectReason: '',
  adminLoading: false,
  adminModerationQueue: null,
  adminContentTab: null,
  adminUser: null,
  adminPageContent: null,
  adminPageSeoStep: null,
  adminAnalyticsSub: null,
  adminAnalyticsRange: null,
  adminGscSub: null,
  adminGscDim: null,
  adminTab: 'dashboard',
  adminCategories: null,
  adminTags: null,
  adminBlogCategories: null,
  adminBlogTags: null,
  adminCatalogColors: null,
  adminCatalogSizes: null,
  adminCatalogBrands: null,
  adminCatalogAttributes: null,
  adminAuthStep: 'phone',
  adminSellers: [],
  adminProducts: null,
  adminOrders: null,
  adminCoupons: null,
  adminTickets: null,
  adminBuyers: null,
  adminSettings: null,
  adminShippingMethods: null
});

export function patchAdminUi(partial) {
  adminUiStore.setState((s) => ({ ...s, ...partial }));
}
