import { createStore } from './createStore.js';

/** دامنه sellerUi — state موقت فرم/مودال/پنل */
export const sellerUiStore = createStore({
  sellerPromoModal: null,
  sellerUser: null,
  sellerOrderDetailId: null,
  sellerOrdersFilter: 'all',
  sellerProductFilter: 'all',
  sellerProductSearch: '',
  sellerProductFormOpen: false,
  sellerProductStep: 1,
  sellerDescEditorOpen: false,
  sellerDescDraft: '',
  sellerDescError: '',
  sellerTaxonomySearch: '',
  sellerProductForm: {},
  sellerMediaToolOpen: false,
  sellerProductDeleteId: null,
  sellerTicketDetailId: null,
  sellerTicketReply: '',
  sellerNewTicketOpen: false,
  sellerNewTicket: { subject: '', body: '' },
  sellerTrackForm: { code: '', carrier: 'پست پیشتاز' },
  sellerCancelForm: { open: false, orderId: null, reason: '' },
  sellerCat: '',
  sellerSort: '',
  sellerDiscountOnly: false,
  sellerCatMenuOpen: false,
  sellerSortMenuOpen: false,
  sellerStickyBar: false,
  sellerBannerIdx: 0,
  sellerFaqOpen: null,
  sellerShareToast: false,
  sellerReportOpen: false,
  sellerReportSent: false,
  sellerListQuery: '',
  sellerCityInput: '',
  sellerSearchOpen: false,
  sellerCityOpen: false,
  sellerFilterSheetOpen: false,
  sellerShopOpen: null,
  sellerGifts: [],
  sellerTab: 'dashboard',
  sellerTaxonomyPicker: null,
  sellerProducts: [],
  sellerOrders: [],
  sellerTickets: [],
  sellerFollowed: {},
  sellerListMinProducts: 0,
  sellerListCities: [],
  sellerListSort: '',
  sellerListMinRating: 0,
  sellerListMaxResponse: 0,
});

export function patchSellerUi(partial) {
  sellerUiStore.setState((s) => ({ ...s, ...partial }));
}
