const noop = async () => ({ ok: false, skipped: true, error: 'SMS disabled' });
export const smsOrderConfirmed = noop;
export const smsOrderCancelled = noop;
export const smsShipped = noop;
export const smsTracking = noop;
export const smsShipDelay = noop;
export const smsDeliveryFail = noop;
export const smsPasswordChanged = noop;
export const smsPhoneChanged = noop;
export const smsOrderReminderSeller = noop;
export const smsOrderDeadlineNear = noop;
export const smsReturnRequestedSeller = noop;
export const smsReturnDecisionBuyer = noop;
export const smsReturnReceived = noop;
export const smsRefundRequested = noop;
export const smsRefundApproved = noop;
export const smsRefundDone = noop;
export const smsRefundFailed = noop;
export default noop;

export const smsOrderPlacedBuyer = noop;
export const smsBankChanged = noop;
export const smsPayoutProcessing = noop;
export const smsPayoutOk = noop;
export const smsPayoutFail = noop;
export const smsDisputeResolved = noop;
export const smsDisputeActionNeeded = noop;
export const smsDisputeOpened = noop;